//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MathParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMathParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class MathParserBaseListener : IMathParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.add_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_expr([NotNull] MathParser.Add_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.add_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_expr([NotNull] MathParser.Add_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.mult_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult_expr([NotNull] MathParser.Mult_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.mult_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult_expr([NotNull] MathParser.Mult_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.exp_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_expr([NotNull] MathParser.Exp_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.exp_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_expr([NotNull] MathParser.Exp_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.final_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinal_expr([NotNull] MathParser.Final_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.final_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinal_expr([NotNull] MathParser.Final_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.exp_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_op([NotNull] MathParser.Exp_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.exp_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_op([NotNull] MathParser.Exp_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.add_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_op([NotNull] MathParser.Add_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.add_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_op([NotNull] MathParser.Add_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.mult_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult_op([NotNull] MathParser.Mult_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.mult_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult_op([NotNull] MathParser.Mult_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.int_declaration_for_iteration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt_declaration_for_iteration([NotNull] MathParser.Int_declaration_for_iterationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.int_declaration_for_iteration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt_declaration_for_iteration([NotNull] MathParser.Int_declaration_for_iterationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] MathParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] MathParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] MathParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] MathParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] MathParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] MathParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.sum_or_product"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum_or_product([NotNull] MathParser.Sum_or_productContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.sum_or_product"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum_or_product([NotNull] MathParser.Sum_or_productContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
