//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MathParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MathParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IMathParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd_expr([NotNull] MathParser.Add_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.mult_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMult_expr([NotNull] MathParser.Mult_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.exp_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_expr([NotNull] MathParser.Exp_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.final_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinal_expr([NotNull] MathParser.Final_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.exp_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_op([NotNull] MathParser.Exp_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.add_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd_op([NotNull] MathParser.Add_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.mult_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMult_op([NotNull] MathParser.Mult_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.int_declaration_for_iteration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt_declaration_for_iteration([NotNull] MathParser.Int_declaration_for_iterationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] MathParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] MathParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] MathParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MathParser.sum_or_product"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSum_or_product([NotNull] MathParser.Sum_or_productContext context);
}
